import { app } from 'electron';
import path from 'path';
import { DownloadManager } from './download-manager.js';
import { fileOperations } from './mods/file-operations.js';
import { deploymentRouting } from './mods/deployment-routing.js';
import { deploymentOperations } from './mods/deployment.js';
import { updateOperations } from './mods/updates.js';
import { ue4ssAndSync } from './mods/ue4ss-and-sync.js';
import { updateCompletion } from './mods/update-completion.js';
import { detailsAndPriority } from './mods/details-and-priority.js';
import { profileOperations } from './mods/profiles.js';
import { onlineInstallation } from './mods/online-installation.js';
import { launchOperations } from './mods/launch.js';
import { catalogOperations } from './mods/catalog.js';
import { installationOperations } from './mods/installation.js';
import { libraryActions } from './mods/library-actions.js';
import { ue4ssConfig } from './mods/ue4ss-config.js';
import { OperationLock, serializeCatalogOperations } from './mods/operation-lock.js';
import { installRequest, type InstallResult } from './mods/install-request.js';
// Operations are grouped by responsibility; the facade preserves the existing Main-process API.
export class ModManager {
modsDir: string;
settingsFile: string;
downloadManager: DownloadManager | null = null;
operationLock = new OperationLock();
activeUpdates = new Map<string, Promise<boolean>>();
updateErrors = new Map<string, string>();
onlineRequests = new Map<number, Promise<InstallResult>>();
gameId = 21179;
    calculateFolderSize = fileOperations.calculateFolderSize;
    fixPriorities = fileOperations.fixPriorities;
    resolveGamePaths = fileOperations.resolveGamePaths;
    deployFile = fileOperations.deployFile;
    extractZip = fileOperations.extractZip;
    deployModFiles = deploymentRouting.deployModFiles;
    deployMod = deploymentOperations.deployMod;
    undeployMod = deploymentOperations.undeployMod;
    setModOrder = deploymentOperations.setModOrder;
    pathExists = deploymentOperations.pathExists;
    existingDeployedFiles = deploymentOperations.existingDeployedFiles;
    downloadFile = updateOperations.downloadFile;
    withMutation = updateOperations.withMutation;
    updateMod = updateOperations.updateMod;
    performUpdate = updateOperations.performUpdate;
    updateAllMods = updateOperations.updateAllMods;
    finalizeUE4SSInstall = ue4ssAndSync.finalizeUE4SSInstall;
    exportCloudSync = ue4ssAndSync.exportCloudSync;
    importCloudSync = ue4ssAndSync.importCloudSync;
    finalizeUpdate = updateCompletion.finalizeUpdate;
    searchOnlineMods = updateCompletion.searchOnlineMods;
    searchBySection = updateCompletion.searchBySection;
    fetchCategories = updateCompletion.fetchCategories;
    fetchNewMods = updateCompletion.fetchNewMods;
    fetchFeaturedMods = updateCompletion.fetchFeaturedMods;
    getAllOnlineMods = updateCompletion.getAllOnlineMods;
    getModDetails = detailsAndPriority.getModDetails;
    setModPriority = detailsAndPriority.setModPriority;
    installUE4SS = detailsAndPriority.installUE4SS;
    getProfilesFilePath = profileOperations.getProfilesFilePath;
    getOnlineModsCachePath = profileOperations.getOnlineModsCachePath;
    getProfiles = profileOperations.getProfiles;
    createProfile = profileOperations.createProfile;
    deleteProfile = profileOperations.deleteProfile;
    loadProfile = profileOperations.loadProfile;
    syncActiveProfile = profileOperations.syncActiveProfile;
    installOnlineMod = installRequest.installOnlineMod;
    startOnlineInstall = onlineInstallation.startOnlineInstall;
    getModChangelog = onlineInstallation.getModChangelog;
    launchGame = launchOperations.launchGame;
    openModsDirectory = catalogOperations.openModsDirectory;
    ensureModsDir = catalogOperations.ensureModsDir;
    getModsFilePath = catalogOperations.getModsFilePath;
    getSettings = catalogOperations.getSettings;
    saveSettings = catalogOperations.saveSettings;
    isPosixLikePath = catalogOperations.isPosixLikePath;
    joinPath = catalogOperations.joinPath;
    relativePath = catalogOperations.relativePath;
    isInsidePath = catalogOperations.isInsidePath;
    getInstalledMods = catalogOperations.getInstalledMods;
    verifyDeployment = installationOperations.verifyDeployment;
    installMod = installationOperations.installMod;
    installPackage = installationOperations.installPackage;
    uninstallMod = libraryActions.uninstallMod;
    toggleMod = libraryActions.toggleMod;
    checkForUpdates = libraryActions.checkForUpdates;
    updateUE4SSModsTxt = ue4ssConfig.updateUE4SSModsTxt;
    getAllFiles = ue4ssConfig.getAllFiles;
constructor(downloadManager?: DownloadManager) {
        if (downloadManager) this.downloadManager = downloadManager;
        this.modsDir = path.join(path.dirname(app.getPath('exe')), 'Mods');
        this.settingsFile = path.join(this.modsDir, 'settings.json');
        if (!app.isPackaged) {
            this.modsDir = path.join(__dirname, '../../Mods');
            this.settingsFile = path.join(this.modsDir, 'settings.json');
        }
        serializeCatalogOperations(this);
    }
}
