import { virtualFS, virtualDirs, normalizePath, resetFS } from './simulation-installer.fixture';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ModManager } from '../../electron/mod-manager';
import path from 'path';
import { execFile } from 'child_process';
describe('Full Installer Lifecycle Simulation', () => {
    let modManager: ModManager;
    beforeEach(() => {
        resetFS();
        vi.clearAllMocks();
        modManager = new ModManager();
        virtualDirs.add('/mock/app/path');
        virtualFS['/game/SparkingZERO.exe'] = 'exe binary content';
    });
    it('should complete a full install, launch, and uninstall cycle', async () => {
        const gamePath = '/game';
        await modManager.saveSettings({ gamePath });
        const settingsPath = '/mods/settings.json';
        const settings = await modManager.getSettings();
        expect(settings.gamePath).toBe(gamePath);
        virtualFS['/downloads/MyMod.zip'] = Buffer.from('dummy zip content');
        const installResult = await modManager.installMod('/downloads/MyMod.zip');
        expect(installResult.success).toBe(true);
        const installedMods = await modManager.getInstalledMods();
        expect(installedMods.length).toBe(1);
        expect(installedMods[0].name).toBe('MyMod');
        expect(installedMods[0].isEnabled).toBe(true);
        const mod = installedMods[0];
        const storedFile = `${mod.folderPath}/mod_file.pak`;
        expect(virtualFS[normalizePath(storedFile)]).toBeDefined();
        const expectedDeployedPath = '/game/SparkingZERO/Content/Paks/~mods/001_mod_file.pak';
        expect(virtualFS[expectedDeployedPath]).toBeDefined();
        await modManager.launchGame();
        expect(execFile).toHaveBeenCalledWith(path.normalize('/game/SparkingZERO.exe'), expect.arrayContaining(['-fileopenlog']), expect.anything(), expect.anything());
        await modManager.toggleMod(mod.id, false);
        expect(virtualFS[expectedDeployedPath]).toBeUndefined();
        expect(virtualFS[normalizePath(storedFile)]).toBeDefined();
        await modManager.toggleMod(mod.id, true);
        expect(virtualFS[expectedDeployedPath]).toBeDefined();
        await modManager.uninstallMod(mod.id);
        expect(virtualFS[expectedDeployedPath]).toBeUndefined();
        expect(virtualFS[normalizePath(storedFile)]).toBeUndefined();
        const finalMods = await modManager.getInstalledMods();
        expect(finalMods.length).toBe(0);
    });
});
describe('Full Installer Lifecycle Simulation', () => {
    let modManager: ModManager;
    beforeEach(() => {
        resetFS();
        vi.clearAllMocks();
        modManager = new ModManager();
        virtualDirs.add('/mock/app/path');
        virtualFS['/game/SparkingZERO.exe'] = 'exe binary content';
    });
    it('should install and manage UE4SS correctly', async () => {
        const gamePath = '/game';
        await modManager.saveSettings({ gamePath });
        const { fetchLatestRelease } = await import('../../electron/github');
        (fetchLatestRelease as any).mockResolvedValue('http://mock.url/ue4ss.zip');
        const tempPath = '/mock/app/path/ue4ss_latest.zip';
        virtualFS[tempPath] = Buffer.from('dummy zip');
        (modManager as any).downloadFile = vi.fn().mockResolvedValue(undefined);
        const result = await modManager.installUE4SS();
        expect(result.success).toBe(true);
        expect(result.message).toContain('UE4SS installed');
        const binariesFile = '/game/SparkingZERO/Binaries/Win64/mod_file.pak';
        expect(virtualFS[binariesFile]).toBeDefined();
    });
});
